matrix:
 - os: osx
    language: generic
    env: PYTHON=3.5.1
 - os: osx
    language: generic
    env: PYTHON=3.6.1

before install:
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi

install:
    - python -m easy_install -U setuptools
    - pip install rumps
    - pip install Pillow

script:
    - python setup.py test

