language: python
python:
  - 3.5
  - 3.6

matrix:
 - os: osx
   language: generic
   env: PYTHON=3.5
 - os: osx
   language: generic
   env: PYTHON=3.6

before install:
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi

install:
 - python -m easy_install -U setuptools
 - pip install Pillow
   # - pip install rumps

script:
 - python setup.py test

