paths:
        pixiv: "/Users/ales/Pictures/pix-girls/"
        girls: "/Users/ales/Pictures/Madchen/"
        img: "/Users/ales/Pictures/"
        meme: "/Users/ales/Pictures/Meme/"
        daytime: "/Users/ales/TimeDayWal/"
        trash: "/Users/ales/.Trash/"
